### ISSUE TITLE
[Test Result] Valve Index, W10

### ISSUE THREAD

**Issue by tort-oise** [egemenertugrul/LuxVR#2]
**Platform:**
 - OS: Windows 10 64-bit
 - HMD: Valve Index
 - LuxVR Version: 1.02
 - Result: mixed results

**Additional context**
UI sliders do not work as intended, similar to the Huawei issue. Otherwise works fine.

**Comment by egemenertugrul** [comment]
Thank you for reporting. I also don't like the fact about buggy UI sliders, I tried to fix it through the base repository OVRLay but no luck. I hope to fix it soon.
